### ISSUE TITLE
Question about multiple alternative steps

### ISSUE THREAD

**Issue by imoneoi** [openai/prm800k#10]
To train PRM, how did you handle multiple alternative steps? Did you supervise every step concatenated with history or only consider a single trajectory? Would supervising every step be inefficient?

For example, supervising every step would like:

```
Step 1: [A, B, C] Chosen: A
Step 2: [D] Chosen: D
Step 2: [E, F] Chosen: E

Training data: [A] [B] [C] [A, D] [A, D, E] [A, D, F]
```

If we supervise only a single trajectory, that would be like:

```
Step 1: [A, B, C] Chosen: A
Step 2: [D] Chosen: D
Step 2: [E, F] Chosen: E

Training data: [A, D, E]
```

**Comment by Huntrr** [comment]
supervise every step. yes it's definitely inefficient, but it's also the simplest approach.
