### ISSUE TITLE
What's the training pipeline of PRM？

### ISSUE THREAD

**Issue by LeopoldACC** [openai/prm800k#3]
Hi, @longouyang @welinder @avital , thanks for your work in PRM. But I want to ask a question is that what's the training pipeline of PRM？
For ORM, we can define the chosen/rejected pairs and use the pairwise loss to supervise the reward model. But I didn't figure out how PRM train, which still confused me after I have read the dataset's structure. It's would be appreciate if anyone can help explaining it or discuss about it. Thanks a lot!

**Comment by qijiaxing** [comment]
As I understand, PRM is treated like a normal LM. In training, it maximize the label (one of <POS>, <NEG>, <NEU>) for the last token of each step answer. That is the label is a special token appended to the step answer.

**Comment by Huntrr** [comment]
@qijiaxing is right.

We train like a normal LM, learning to predict a single rating token (-1, 0, 1) given a problem and the solution up to the current step.
