### ISSUE TITLE
Questions about implmentation detail.

### ISSUE THREAD

**Issue by lxww302** [openai/prm800k#7]
Thanks for your excellent work on open-sourcing the data. I have a few questions regarding to the implmentation details.
1. You mentioned "We train like a normal LM, learning to predict a single rating token (-1, 0, 1) given a problem and the solution up to the current step". In my understanding, the input is something like [question_tokens, sep_token, solution_step1_tokens, rating_token_for_1, solution_step2_tokens, rating_token_for_0, solution_step3_tokens, rating_token_for_-1]. You use different token for different score, and when predicting the rating_token_for_step3, the model has information access to the rating score for step1 and step2 because they are present in the context. The training loss is the log-likelihood of these rating tokens over the whole vocabulary, am I correct ?
2.  You also mentioned "it suffices to perform a single PRM forward pass over the whole solution". I am not sure how that worked out. My best guess is that a rating placeholder token is appended at the end of every step. The input is something like [question_tokens, sep_token, solution_step1_tokens, rating_placeholder_token, solution_step2_tokens, rating_placeholder_token, solution_step3_tokens, rating_placeholder_token]. You take the log-likelihood of these rating tokens and normalize it over 3 tokens (rating_token_for_-1, rating_token_for_0, rating_token_for_1). Is it correct ?

**Comment by Huntrr** [comment]
We did an even simpler setup! The examples look like:

`prompt=[question_tokens, solution_step1_tokens, request_rating_token, placeholder_token, solution_step2_tokens, request_rating_token, placeholder_token, solution_step3_tokens, request_rating_token]`

`completion=[rating_for_step_3]`

and train log likelihood over whole vocab for just the completion

1. the model doesn't get to see step1, step2 ratings, it just sees the placeholders
2. basically correct! we just put in all the placeholders and do a forward pass and normalize the ratings for the log probs on the placeholder tokens

**Comment by gongyaguang-tal** [comment]
@Huntrr I have several questions. Hope for your reply. 
1) How to define the placeholder_token and request_rating_token? Will they pose a negative impact on continuity of the total solution?
2) Which could be better, if I add a new classifier head instead of training the way LM does?

**Comment by Huntrr** [comment]
1. i think most open source LLMs have an idea of "special tokens" you can use as placeholder tokens. no negative impact on "continuity" because we don't sample solutions from the PRM model
2. these should be equivalent for the purposes of this project.

please open a new issue if you have questions
