### ISSUE TITLE
Questions about the solution-level score.

### ISSUE THREAD

**Issue by lxww302** [openai/prm800k#8]
Hi guys, thanks again for your excellent work on PRM. I also have some questions regarding to the solution-level score.
1. In the paper you mentioned "we consider neutral steps to be positive, and we define the solution score to be the product of step-level scores". In my understanding, this setup will give a high score to short solutions that make some progress but do not arrive at a final answer. This may not be a big problem in best-of-1860 senario but will definitely be a problem when used in RLHF or Best-of-N when N is much larger. What's your opinion on this ?
2. You also mentioned "Using the product instead of the minimum as the reduction does create a slight bias against solutions with a larger number of steps". I went through the prediction file and found that around 60% of response pairs, smaller PRM scores have larger number of steps. When used in RLHF, this will result in shorter solutions have higher PRM scores. what is your recommandation when applying this in RLHF ?

**Comment by Huntrr** [comment]
Good questions. This gets at a subtle & tricky problem with PRMs on how to treat the "final answer" step differently from normal steps.

1. We never pick incomplete solutions in the best-of-N procedure, so this doesn't affect the PRM. For RLHF you can also filter our incomplete solutions fairly easily, though it's trickier if you try to do RLHF at a step-level!
2. No concrete recommendations (besides filtering out incomplete solutions) but we think figuring out how to apply RLHF here is an interesting area for further research 😉
